services:
  - type: web
    name: vidbuddy
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    buildpacks:
      - https://github.com/render-examples/heroku-buildpack-nodejs.git
      - https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git
      - heroku/python
