services:
  - type: web
    name: vidbuddy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    buildpacks:
      - heroku/python
      - https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git
